### ISSUE TITLE
Nullpointer at the Archive object

### ISSUE THREAD

**Issue by yildirimadiguzel** [edmund-wagner/junrar#2]
Hi,

I am encountering with Nullpointer exception when I am instantiating the Archive object.  This file is valid and can be extracted with some other applications like "winrar" on windows  and "zipeg" on mac os x. The trace like below. You can download the rar file from 

http://78.47.144.62/sample.rar

Jul 25, 2011 4:49:35 PM de.innosystec.unrar.Archive setFile
WARNING: exception in archive constructor maybe file is encrypted or currupt
java.lang.NullPointerException
    at de.innosystec.unrar.Archive.readHeaders(Archive.java:234)
    at de.innosystec.unrar.Archive.setFile(Archive.java:124)
    at de.innosystec.unrar.Archive.<init>(Archive.java:108)
    at de.innosystec.unrar.Archive.<init>(Archive.java:96)
    at com.xxxx.common.service.FileIOService.extract(FileIOService.java:16)
    at com.xxxx.common.service.FileIOServiceTest.shouldFindReleatedTextFileInCorrectFolderWhenRarFileExists(FileIOServiceTest.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:274)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:242)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:58)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:240)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:48)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:233)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:303)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by edmund-wagner** [comment]
hmm i get this message when i try to extract the files (only have linux to test)

$ unrar  v sample.rar 
UNRAR 4.00 beta 3 freeware      Copyright (c) 1993-2010 Alexander Roshal

sample.rar is not RAR archive

is that rar encrypted? thats not supported by junrar ...

**Comment by mpadilha** [comment]
Hi, I get the same error for archives created with the "RAR" Archive Format in a recent WinRar application. If I change the Archive Format to "RAR4" (which seems to be older) then junrar can open it fine.
