### ISSUE TITLE
junjar seems has problem with this rar file

### ISSUE THREAD

**Issue by xuemingshen** [edmund-wagner/junrar#4]
Hi,

It appears the junjar has problem to work on some type of files. For example with my libfontmanager.rar, which is just created by winrar4.01. It includes two files, one is
libfontmanager.so, which is a linux .so file from the jdk binary, other is the text file jvm.cfg.

junjar works fine with jvm.cfg, but throws an exception for the libfontmanger.so. This is
not the only one that junjar does not like, when try to junjar a .rar file including the whole
linux jdk binary (with source and all the binaries), it fails on lots of .so files, though works
fine as well on the rest (including lots of .so file as well).

It appears the crc32 calculation is correct, the output bytes of the libfontmanager.so indeed
has different bits compare to its source. So I guess something is wrong during the decoding.

I don't know how to upload the test case libfontmanager.rar here, so I parked it at

http://www.filedropper.com/libfontmanager

It should be safe to download that file by clicking "Download this file". Let me know if an email with an attachment is more comfortable, the .rar file is about 100K.

Thanks!
-Xueming

---

$ /cygdrive/d/jdk6/bin/java -cp "./target/java-unrar-0.6-SNAPSHOT.jar;./" Test  test/libfontmanager
.rar dst
extracting: libfontmanager.so
de.innosystec.unrar.exception.RarException: crcError
        at de.innosystec.unrar.Archive.doExtractFile(Archive.java:473)
        at de.innosystec.unrar.Archive.extractFile(Archive.java:443)
        at Test.extractArchive(Test.java:82)
        at Test.extractArchive(Test.java:38)
        at Test.main(Test.java:43)
extracting: jvm.cfg

http://www.filedropper.com/libfontmanager

**Comment by i30817** [comment]
Is it a solid archive? :) It's a little bit tricky to extract those. I have a hack that does it somewhere:
http://code.google.com/p/bookjar-utils/source/browse/BookJar-utils/src/util/io/compressed/RarExtractor.java

More than a little bit obfuscated because it's in a framework, but basically, to extract a solid archive beyond the first file, you need to do it "in order". Extract the first, extract the second etc.

I do this by keeping a index of the "current file" in the stream, and when asked for a file in the archive i extract "until the file index" into a black hole, then extract the real file.
This allows me both random access and sequential extraction with less fuss.

**Comment by xuemingshen** [comment]
Hi
Just checked back my old issues. Did not have time to dig deeper the past "months".
Would you please explain in a little details? I appears the "RarExtractor.java" on code.google.com can't not be accessed (permission deny...)

Thanks!

**Comment by i30817** [comment]
the project repository changed
http://code.google.com/p/bookjar/source/browse/bookjar-decompress/src/decompress/RarExtractor.java

But basically you can recreate that stuff by knowing that a solid rar archive outputstream of a file that is not the first, will only give correct bytes if the archive had 'extracted' the previous files first - the outputstream that the previous file go to doesn't matter - this is because the Archive class has state, as long as you don't close the Archive in between extractions, you'll be able to extract a solid archive file (but if you're extracting all files in the archive, you better order the extractions by the archive 'natural' order so as not to have to 'reset' the state of the Archive a lot)

**Comment by i30817** [comment]
Repository changed again: https://code.google.com/p/bookjar/source/browse/subprojects/bookjar-decompress/src/i3/decompress/RarExtractor.java
